
remote_theme: pmarsceill/just-the-docs

exclude: ["stage1/", "README.md"]

title: Data Science
search_enabled: true
aux_links:
  "View GitHub Repository":
    - "//github.com/chen-xanadu/cs839-website"
